#!/usr/bin/python3
# -*- coding: utf-8 -*-
# [Gedit Tool]
# Name=Export to HTML
# Name[fr]=Exporter en HTML
# Shortcut=<Control><Alt>h
# Languages=markdown
# Applicability=all
# Input=selection-document
# Output=new-document
# Save-files=nothing

import codecs
import os
import sys
import markdown
from configparser import ConfigParser

# Configuration.

try:
	import xdg.BaseDirectory
except ImportError:
	homeDir = os.environ.get("HOME")
	xdgConfigHome = os.path.join(homeDir, ".config")
else:
	xdgConfigHome = xdg.BaseDirectory.xdg_config_home

confDir =  os.path.join(xdgConfigHome, "gedit")
confFile =  os.path.join(confDir, "gedit-markdown.ini")
parser = ConfigParser()

if os.path.isfile(confFile):
	parser.read(confFile)
	markdownExtensions = parser.get("markdown-preview", "extensions")
else:
	markdownExtensions = "extra toc"
markdownExtensionsList = markdownExtensions.split()

htmlTemplate = ""
with open("template.html", 'r') as f:
	htmlTemplate = f.read()

text = sys.stdin.read()
print("<!-- Markdown => HTML -->")

print(htmlTemplate % markdown.markdown(text, extensions=markdownExtensionsList))
